###
# Mark Silvis
# CS 1655
# Assignment 1
# Makefile
###

# compiler
JCC = javac

default: preproc.class indexer.class ranker.class

preproc.class: preproc.java
	$(JCC) preproc.java

indexer.class: indexer.java
	$(JCC) indexer.java

ranker.class: ranker.java
	$(JCC) ranker.java
	